package com.servoy.eclipse.developer.mcp.services;

import java.io.BufferedReader;
import java.io.File;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.TimeUnit;

import org.eclipse.core.resources.ResourcesPlugin;
import org.eclipse.e4.core.di.annotations.Creatable;

import com.servoy.eclipse.core.ServoyModelManager;
import com.servoy.eclipse.model.nature.ServoyProject;
import com.servoy.eclipse.ngclient.ui.Activator;
import com.servoy.j2db.persistence.IServerInternal;
import com.servoy.j2db.server.shared.ApplicationServerRegistry;

/**
 * Runs Cypress test specs (.spec.cy.js) against Servoy forms using npx cypress run.
 * Cypress is installed locally in .metadata/.plugins/com.servoy.eclipse.copilot/cypress/.
 * Spec files live next to the .frm file in forms/ directory.
 */
@Creatable
@SuppressWarnings("restriction")
public class FormSpecRunner
{
	private static final String MCP_PLUGIN_DIR = "com.servoy.eclipse.developer.mcp";
	private static final String CYPRESS_DIR = "cypress";
	private static final int DEFAULT_TIMEOUT_SECONDS = 60;

	private final FormSpecGenerator specGenerator = new FormSpecGenerator();

	/**
	 * Runs the Cypress spec for the given form using 'npx cypress run'.
	 *
	 * @param formName the form whose .spec.cy.js to run
	 * @param headless true for headless (default), false for headed (debugging)
	 * @return test results output
	 */
	public String runSpec(String formName, boolean headless)
	{
		try
		{
			ServoyProject activeProject = ServoyModelManager.getServoyModelManager().getServoyModel().getActiveProject();
			if (activeProject == null)
			{
				return "Error: No active Servoy project.";
			}

			Path specFilePath = specGenerator.getSpecFilePath(formName);
			if (specFilePath == null || !Files.exists(specFilePath))
			{
				return "Error: Spec file not found: forms/" + formName + ".spec.cy.js. Use showFormInBrowser first to auto-generate it.";
			}

			Path cypressDir = getCypressDir();
			String setupError = ensureCypressInstalled(cypressDir);
			if (setupError != null)
			{
				return setupError;
			}

			String solutionName = activeProject.getSolution().getName();
			int port = ApplicationServerRegistry.get().getWebServerPort();
			String baseUrl = "http://localhost:" + port + "/solution/" + solutionName + "/index.html";

			ensureCypressConfig(cypressDir, baseUrl);

			File nodePath = getNodePath();
			if (nodePath == null)
			{
				return "Error: Bundled Node.js not available.";
			}

			String npxPath = nodePath.getParent() + File.separator + "npx.cmd";
			if (!new File(npxPath).exists())
			{
				npxPath = nodePath.getParent() + File.separator + "npx";
			}

			List<String> command = new ArrayList<>();
			command.add(npxPath);
			command.add("cypress");
			command.add("run");
			command.add("--spec");
			command.add(specFilePath.toString());
			command.add("--config-file");
			command.add(cypressDir.resolve("cypress.config.js").toString());
			if (!headless)
			{
				command.add("--headed");
			}

			ProcessBuilder pb = new ProcessBuilder(command);
			pb.directory(activeProject.getProject().getLocation().toFile());
			pb.redirectErrorStream(true);
			pb.environment().put("NODE_PATH", cypressDir.resolve("node_modules").toString());
			Process process = pb.start();

			StringBuilder output = new StringBuilder();
			try (BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream(), StandardCharsets.UTF_8)))
			{
				String line;
				while ((line = reader.readLine()) != null)
				{
					output.append(line).append("\n");
				}
			}

			boolean finished = process.waitFor(DEFAULT_TIMEOUT_SECONDS, TimeUnit.SECONDS);
			if (!finished)
			{
				process.destroyForcibly();
				return "Error: Cypress test timed out after " + DEFAULT_TIMEOUT_SECONDS + " seconds.";
			}

			String rawOutput = output.toString();

			if (process.exitValue() == 0)
			{
				return "**Form Spec Results: " + formName + "**\n\nAll tests passed!\n\n" + rawOutput;
			}
			else
			{
				return "**Form Spec Results: " + formName + "**\n\nSome tests failed:\n\n" + rawOutput;
			}
		}
		catch (Exception e)
		{
			return "Error running spec: " + e.getMessage();
		}
	}

	/**
	 * Writes cypress.config.js with baseUrl for the running Servoy solution.
	 */
	private void ensureCypressConfig(Path cypressDir, String baseUrl)
	{
		try
		{
			Path configFile = cypressDir.resolve("cypress.config.js");
			String config = "// Auto-generated by Servoy MCP - do not edit manually\n" +
				"const { defineConfig } = require('cypress');\n\n" +
				"module.exports = defineConfig({\n" +
				"  e2e: {\n" +
				"    baseUrl: '" + baseUrl + "',\n" +
				"    supportFile: false,\n" +
				"    specPattern: '**/*.spec.cy.js',\n" +
				"    defaultCommandTimeout: 10000,\n" +
				"    pageLoadTimeout: 30000,\n" +
				"    video: false,\n" +
				"    screenshotOnRunFailure: false,\n" +
				"  },\n" +
				"});\n";
			Files.writeString(configFile, config, StandardCharsets.UTF_8);
		}
		catch (Exception e)
		{
			// Non-fatal
		}
	}

	private Path getCypressDir()
	{
		Path workspaceRoot = ResourcesPlugin.getWorkspace().getRoot().getLocation().toFile().toPath();
		Path metadataPlugins = workspaceRoot.getParent().resolve(".metadata").resolve(".plugins");
		return metadataPlugins.resolve(MCP_PLUGIN_DIR).resolve(CYPRESS_DIR);
	}

	private File getNodePath()
	{
		try
		{
			Activator ngActivator = Activator.getInstance();
			if (ngActivator == null) return null;
			ngActivator.extractNode();
			ngActivator.createNPMCommand(new File("."), java.util.List.of("--version"));
			var field = Activator.class.getDeclaredField("nodePath");
			field.setAccessible(true);
			return (File)field.get(ngActivator);
		}
		catch (Exception e)
		{
			return null;
		}
	}

	public String executeTestSetup(String serverName, String tableName, java.util.Map<String, Object> columnValues)
	{
		if (serverName == null || tableName == null || columnValues == null || columnValues.isEmpty())
			return "Error: serverName, tableName, and columnValues are required.";

		try
		{
			if (!com.servoy.j2db.server.shared.ApplicationServerRegistry.exists())
				return "Error: Servoy application server is not running.";

			IServerInternal server = (IServerInternal)ApplicationServerRegistry.get().getServerManager().getServer(serverName, false, false);
			if (server == null) return "Error: Database server '" + serverName + "' not found.";

			StringBuilder cols = new StringBuilder();
			StringBuilder placeholders = new StringBuilder();
			List<Object> values = new ArrayList<>();

			for (java.util.Map.Entry<String, Object> entry : columnValues.entrySet())
			{
				if (cols.length() > 0)
				{
					cols.append(", ");
					placeholders.append(", ");
				}
				cols.append(entry.getKey());
				placeholders.append("?");
				values.add(entry.getValue());
			}

			String sql = "INSERT INTO " + tableName + " (" + cols + ") VALUES (" + placeholders + ")";

			try (Connection conn = server.getRawConnection())
			{
				try (PreparedStatement ps = conn.prepareStatement(sql))
				{
					for (int i = 0; i < values.size(); i++)
					{
						ps.setObject(i + 1, values.get(i));
					}
					ps.executeUpdate();
				}
				conn.commit();
			}

			return "Test setup: inserted 1 row into " + serverName + "." + tableName;
		}
		catch (Exception e)
		{
			return "Error in test setup: " + e.getMessage();
		}
	}

	public String executeTestTeardown(String serverName, String tableName, String whereColumn, Object whereValue)
	{
		if (serverName == null || tableName == null || whereColumn == null || whereValue == null)
			return "Error: serverName, tableName, whereColumn, and whereValue are required.";

		try
		{
			if (!com.servoy.j2db.server.shared.ApplicationServerRegistry.exists())
				return "Error: Servoy application server is not running.";

			IServerInternal server = (IServerInternal)ApplicationServerRegistry.get().getServerManager().getServer(serverName, false, false);
			if (server == null) return "Error: Database server '" + serverName + "' not found.";

			String sql = "DELETE FROM " + tableName + " WHERE " + whereColumn + " = ?";
			int deleted = 0;

			try (Connection conn = server.getRawConnection())
			{
				try (PreparedStatement ps = conn.prepareStatement(sql))
				{
					ps.setObject(1, whereValue);
					deleted = ps.executeUpdate();
				}
				conn.commit();
			}

			return "Test teardown: deleted " + deleted + " row(s) from " + serverName + "." + tableName + " where " + whereColumn + " = '" + whereValue + "'";
		}
		catch (Exception e)
		{
			return "Error in test teardown: " + e.getMessage();
		}
	}

	/**
	 * Ensures Cypress is installed locally in the .metadata plugins directory.
	 */
	private String ensureCypressInstalled(Path cypressDir)
	{
		try
		{
			boolean needsInstall = !Files.exists(cypressDir.resolve("node_modules/cypress"));

			if (needsInstall)
			{
				Files.createDirectories(cypressDir);
				String packageJson = "{\n" +
					"  \"name\": \"servoy-cypress\",\n" +
					"  \"version\": \"1.0.0\",\n" +
					"  \"private\": true,\n" +
					"  \"dependencies\": {\n" +
					"    \"cypress\": \"^13.0.0\"\n" +
					"  }\n" +
					"}\n";
				Files.writeString(cypressDir.resolve("package.json"), packageJson, StandardCharsets.UTF_8);

				File nodePath = getNodePath();
				if (nodePath == null) return "Error: Node.js not available.";

				String npmPath = nodePath.getParent() + File.separator + "npm.cmd";
				if (!new File(npmPath).exists())
				{
					npmPath = nodePath.getParent() + File.separator + "npm";
				}

				ProcessBuilder pb = new ProcessBuilder(npmPath, "install");
				pb.directory(cypressDir.toFile());
				pb.redirectErrorStream(true);
				Process p = pb.start();
				try (BufferedReader reader = new BufferedReader(new InputStreamReader(p.getInputStream(), StandardCharsets.UTF_8)))
				{
					while (reader.readLine() != null) { /* drain */ }
				}
				p.waitFor(180, TimeUnit.SECONDS);

				if (p.exitValue() != 0) return "Error: npm install failed in cypress directory.";
			}
			return null;
		}
		catch (Exception e)
		{
			return "Error setting up Cypress: " + e.getMessage();
		}
	}
}
