/*
 This file belongs to the Servoy development and deployment environment, Copyright (C) 2026 Servoy BV

 This program is free software; you can redistribute it and/or modify it under
 the terms of the GNU Affero General Public License as published by the Free
 Software Foundation; either version 3 of the License, or (at your option) any
 later version.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.

 You should have received a copy of the GNU Affero General Public License along
 with this program; if not, see http://www.gnu.org/licenses or write to the Free
 Software Foundation,Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301
 */
package com.servoy.eclipse.servoypilot.services;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import com.servoy.eclipse.servoypilot.exceptions.ValidationException;


/**
 * Validator for documentation application.
 * 
 * Validates:
 * - UUID preservation (CRITICAL - UUIDs must never change)
 * - JSDoc syntax correctness
 */
public class DocumentationValidatorService
{
	private static final Pattern UUID_PATTERN = Pattern.compile("@UUID\\s+([a-f0-9-]{36})");
	private static final Pattern JSDOC_BLOCK_PATTERN = Pattern.compile("/\\*\\*.*?\\*/", Pattern.DOTALL);
	private static final Pattern PARAM_TAG_PATTERN = Pattern.compile("@param\\s+\\{[^}]+\\}");

	/**
	 * Validates that UUIDs are preserved between original and modified content.
	 * 
	 * @param originalContent Original file content
	 * @param newContent Modified file content
	 * @throws ValidationException if UUIDs don't match
	 */
	public void validateUUIDs(String originalContent, String newContent) throws ValidationException
	{
		List<String> originalUUIDs = extractUUIDs(originalContent);
		List<String> newUUIDs = extractUUIDs(newContent);

		if (originalUUIDs.size() != newUUIDs.size())
		{
			throw new ValidationException(
				"UUID count mismatch! Original: " + originalUUIDs.size() +
					", Modified: " + newUUIDs.size() +
					"\nOriginal UUIDs: " + originalUUIDs +
					"\nModified UUIDs: " + newUUIDs);
		}

		for (int i = 0; i < originalUUIDs.size(); i++)
		{
			if (!originalUUIDs.get(i).equals(newUUIDs.get(i)))
			{
				throw new ValidationException(
					"UUID modification detected at position " + i +
						"!\nOriginal: " + originalUUIDs.get(i) +
						"\nModified: " + newUUIDs.get(i));
			}
		}
	}

	/**
	 * Extracts all UUIDs from content.
	 * 
	 * @param content File content
	 * @return List of UUID strings found
	 */
	public List<String> extractUUIDs(String content)
	{
		List<String> uuids = new ArrayList<>();
		if (content != null)
		{
			Matcher matcher = UUID_PATTERN.matcher(content);
			while (matcher.find())
			{
				uuids.add(matcher.group(1));
			}
		}
		return uuids;
	}

	/**
	 * Restores original UUIDs in new JSDoc if AI modified them.
	 * Silently fixes UUID corruption by replacing AI-generated UUIDs with originals.
	 * 
	 * @param newJSDoc JSDoc generated by AI (may have wrong UUIDs)
	 * @param originalUUIDs List of original UUIDs from code
	 * @return Fixed JSDoc with original UUIDs restored
	 */
	public String restoreUUIDs(String newJSDoc, List<String> originalUUIDs)
	{
		if (originalUUIDs == null || originalUUIDs.isEmpty())
		{
			return newJSDoc;
		}

		List<String> newUUIDs = extractUUIDs(newJSDoc);
		if (newUUIDs.isEmpty())
		{
			return newJSDoc;
		}

		String result = newJSDoc;
		
		// Replace each UUID in new JSDoc with corresponding original UUID
		for (int i = 0; i < Math.min(newUUIDs.size(), originalUUIDs.size()); i++)
		{
			String newUUID = newUUIDs.get(i);
			String originalUUID = originalUUIDs.get(i);
			
			if (!newUUID.equals(originalUUID))
			{
				// Replace AI's UUID with original
				result = result.replaceFirst(
					"@UUID\\s+" + Pattern.quote(newUUID),
					"@UUID " + originalUUID
				);
			}
		}

		return result;
	}

	/**
	 * Validates JSDoc syntax in content.
	 * Checks that all JSDoc blocks are properly formatted.
	 * 
	 * @param content File content with JSDoc
	 * @throws ValidationException if JSDoc syntax is invalid
	 */
	public void validateJSDocSyntax(String content) throws ValidationException
	{
		if (content != null)
		{
			Matcher matcher = JSDOC_BLOCK_PATTERN.matcher(content);

			while (matcher.find())
			{
				String jsdoc = matcher.group();

				// Must start with /** and end with */
				if (!jsdoc.startsWith("/**") || !jsdoc.endsWith("*/"))
				{
					String preview = jsdoc.substring(0, Math.min(50, jsdoc.length()));
					throw new ValidationException("Invalid JSDoc syntax: " + preview);
				}

				// Check for @param tags without type annotations
				if (jsdoc.contains("@param") && !PARAM_TAG_PATTERN.matcher(jsdoc).find())
				{
					String preview = jsdoc.substring(0, Math.min(100, jsdoc.length()));
					throw new ValidationException("@param tag missing type annotation: " + preview);
				}
			}
		}
	}
}
