source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               resources/,\
               lib/mcp-json-jackson2-1.1.2.jar,\
               lib/tomcat-embed-core-11.0.21.jar
